version: 2.1

orbs:
  silta: silta/silta@dev:master

executors:
  node16:
    docker:
      - image: wunderio/silta-cicd:circleci-php8.0-node16-composer2-v1
  node22:
    docker:
      - image: wunderio/silta-cicd:circleci-php8.2-node22-composer2-test20240613

jobs:
  site-test:
    resource_class: small
    docker:
      - image: alpine/curl
    steps:
      - site-query:
          site_url: https://master.simple-project-k8s.dev.wdr.io
      - site-query:
          site_url: https://master.simple-project-k8s.silta-aks.wdr.io

commands:
  site-query:
    parameters:
      site_url:
        type: string
    steps:
      - run:
          name: Validate site url <<parameters.site_url>>
          command: |          
            curl -u $SITE_TEST_BAUTH <<parameters.site_url>>

workflows:
  version: 2
  build_deploy:
    jobs:
      - silta/simple-build-deploy: &build-deploy
          name: 'Build & deploy master'
          executor: node22
          build_folder: hello

          # Use a local chart during development.
          # Don't copy this! We only use following 2 lines for chart development in this repository.
          chart_name: "./charts/simple"
          chart_repository: ""

          #Executes after logging into cluster, docker
          pre-release:
            - run:
                name: Build local helm dependencies
                command: |
                  helm dependency build ./charts/simple
            - run:
                name: Dry-run helm install
                command: |
                  http_proxy=$SILTA_PROXY HTTPS_PROXY=$SILTA_PROXY \
                    helm install --dry-run --generate-name ./charts/simple --values charts/simple/test.values.yaml
          context: 'silta_dev'
          silta_config: silta/silta.yml
          filters:
            branches:
              only:
                - master

      - approval:
          type: approval
          name: "Deployment approval"
          filters:
            branches:
              ignore:
                - production
                - master
                - /feature\/test-cluster\/.*/
                - /feature\/aws\/.*/
                - cm-upgrade

      - silta/simple-build-deploy:
          <<: *build-deploy
          name: 'Build & deploy'
          requires:
            - "Deployment approval"
          filters:
            branches:
              ignore:
                - production
                - master
                - /feature\/test-cluster\/.*/
                - /feature\/aws\/.*/
                - cm-upgrade

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration for the test cluster deployments
          <<: *build-deploy
          name: 'Build & deploy master to aks cluster'
          silta_config: silta/silta.yml
          context: silta_aks
          filters:
            branches:
              only:
                - master

      - site-test:
          name: 'Site test'
          requires:
            - 'Build & deploy'
            - 'Build & deploy master to aks cluster'
          filters:
            branches:
              only:
                - master

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration for the test cluster deployments
          <<: *build-deploy
          name: 'Build & deploy to test cluster'
          silta_config: silta/silta.yml,silta/silta-test.yml
          context: silta_test
          filters:
            branches:
              only:
                - /feature\/test-cluster\/.*/

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration for the aws cluster deployments
          <<: *build-deploy
          name: 'Build & deploy to aws cluster'
          silta_config: silta/silta.yml,silta/silta-aws.yml
          context: silta_aws
          filters:
            branches:
              only:
                - /feature\/aws\/.*/

  weekly-build:
    triggers:
      - schedule:
          cron: '0 8 * * 5'
          filters:
            branches:
              only:
                - master
    jobs:
      - silta/simple-build-deploy: &build-deploy
          name: 'Build & deploy master'
          executor: node22
          build_folder: hello

          # Use a local chart during development.
          # Don't copy this! We only use following 2 lines for chart development in this repository.
          chart_name: "./charts/simple"
          chart_repository: ""

          #Executes after logging into cluster, docker
          pre-release:
            - run:
                name: Build local helm dependencies
                command: |
                  helm dependency build ./charts/simple
            - run:
                name: Dry-run helm install
                command: |
                  helm install --dry-run --generate-name ./charts/simple --values charts/simple/test.values.yaml
          context: 'silta_dev'
          silta_config: silta/silta.yml
          filters:
            branches:
              ignore:
                - production
                - /feature\/test-cluster\/.*/
                - /feature\/aws\/.*/
                - cm-upgrade

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration for the test cluster deployments
          <<: *build-deploy
          name: 'Build & deploy master to aks cluster'
          silta_config: silta/silta.yml
          context: silta_aks
          filters:
            branches:
              only:
                - master

      - site-test:
          name: 'Site test'
          requires:
            - 'Build & deploy master'
            - 'Build & deploy master to aks cluster'
          filters:
            branches:
              only:
                - master
