version: 2.1

orbs:
  silta: silta/silta@dev:master

executors:
  node16:
    docker:
      - image: wunderio/silta-cicd:circleci-php8.0-node16-composer2-test

jobs:
  site-test:
    docker:
      - image: alpine/curl
    steps:
      - site-query:
          site_url: https://master.simple-project-k8s.dev.wdr.io
      - site-query:
          site_url: https://master.simple-project-k8s.silta-aks.wdr.io

commands:
  site-query:
    parameters:
      site_url:
        type: string
    steps:
      - run:
          name: Validate site url <<parameters.site_url>>
          command: |          
            curl -u $SITE_TEST_BAUTH <<parameters.site_url>>

workflows:
  version: 2
  build_deploy:
    jobs:
      - silta/simple-build-deploy: &build-deploy
          name: 'Build & deploy'
          executor: node16
          build_folder: hello

          # Use a local chart during development. 
          # Don't copy this! We only use following 2 lines for chart development in this repository.
          chart_name: "./charts/simple"
          chart_repository: ""

          #Executes after logging into cluster, docker
          pre-release:
            - run:
                name: Build local helm dependencies
                command: |
                  helm dependency build ./charts/simple
            - run:
                name: Dry-run helm install
                command: |
                  helm install --dry-run --generate-name ./charts/simple --values charts/simple/test.values.yaml
          context: 'silta_dev'
          silta_config: silta/silta.yml
          filters:
            branches:
              ignore:
                - production
                - /feature\/test-cluster\/.*/
                - /feature\/aws\/.*/
                - cm-upgrade
                - feature/amazon-cluster

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration for the test cluster deployments
          <<: *build-deploy
          name: 'Build & deploy master to aks cluster'
          silta_config: silta/silta.yml
          context: silta_aks
          filters:
            branches:
              only: 
                - master

      - site-test:
          name: 'Site test'
          requires:
            - 'Build & deploy'
            - 'Build & deploy master to aks cluster'
          filters:
            branches:
              only: 
                - master

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration for the test cluster deployments
          <<: *build-deploy
          name: 'Build & deploy to test cluster'
          silta_config: silta/silta.yml,silta/silta-test.yml
          context: silta_test
          filters:
            branches:
              only: 
                - /feature\/test-cluster\/.*/

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration for the aws cluster deployments
          <<: *build-deploy
          name: 'Build & deploy to aws cluster'
          silta_config: silta/silta.yml,silta/silta-aws.yml
          context: silta_aws_poc
          codebase-build:
            - run:
                name: Download feature branch build of silta cli
                command: |
                  curl -sL https://github.com/wunderio/silta-cli/releases/download/test/silta-test-linux-amd64.tar.gz | tar xz -C ~/.local/bin
            - run:
                name: install kubectl
                command: |
                  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
                  && sudo apt-get install apt-transport-https ca-certificates \
                  && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - \
                  && sudo apt-get update && sudo apt-get install kubectl
          filters:
            branches:
              only: 
                - /feature\/aws\/.*/
                - feature/amazon-cluster

  weekly-build:
    triggers:
      - schedule:
          cron: '0 8 * * 5'
          filters:
            branches:
              only:
                - master
    jobs:
      - silta/simple-build-deploy: &build-deploy
          name: 'Build & deploy'
          executor: node16
          build_folder: hello

          # Use a local chart during development. 
          # Don't copy this! We only use following 2 lines for chart development in this repository.
          chart_name: "./charts/simple"
          chart_repository: ""

          #Executes after logging into cluster, docker
          pre-release:
            - run:
                name: Build local helm dependencies
                command: |
                  helm dependency build ./charts/simple
            - run:
                name: Dry-run helm install
                command: |
                  helm install --dry-run --generate-name ./charts/simple --values charts/simple/test.values.yaml
          context: 'silta_dev'
          silta_config: silta/silta.yml
          filters:
            branches:
              ignore:
                - production
                - /feature\/test-cluster\/.*/
                - /feature\/aws\/.*/
                - cm-upgrade
                - feature/amazon-cluster

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration for the test cluster deployments
          <<: *build-deploy
          name: 'Build & deploy master to aks cluster'
          silta_config: silta/silta.yml
          context: silta_aks
          filters:
            branches:
              only: 
                - master

      - site-test:
          name: 'Site test'
          requires:
            - 'Build & deploy'
            - 'Build & deploy master to aks cluster'
          filters:
            branches:
              only: 
                - master
