version: 2.1

orbs:
  silta: silta/silta@dev:master

executors:
  silta-latest:
    docker:
      - image: wunderio/silta-circleci:latest

workflows:
  version: 2
  build_deploy:
    jobs:
      - silta/simple-build-deploy: &build-deploy
          name: 'Silta build & deploy'
          executor: silta-latest
          build_folder: hello

          # Use a local chart during development. 
          # Don't copy this! We only use following 2 lines for chart development in this repository.
          chart_name: "./charts/simple"
          chart_repository: ""

          #Executes after logging into cluster, docker
          pre-release:
            - run:
                name: Build local helm dependencies
                command: |
                  helm dependency build ./charts/simple
            - run:
                name: Dry-run helm install
                command: |
                  helm install --dry-run --generate-name ./charts/simple --values charts/simple/test.values.yaml
          context: 'silta_dev'
          silta_config: silta/silta.yml
          filters:
            branches:
              ignore:
                - production
                - /feature\/test\/.*/
                - /feature\/aws\/.*/
                - cm-upgrade

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration for the test cluster deployments
          <<: *build-deploy
          name: Silta build & deploy to test cluster
          silta_config: silta/silta.yml,silta/silta-test.yml
          context: silta_test
          filters:
            branches:
              only: 
                - /feature\/test\/.*/
                - cm-upgrade

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration for the aws cluster deployments
          <<: *build-deploy
          name: Silta build & deploy to aws cluster
          silta_config: silta/silta.yml,silta/silta-aws.yml
          context: silta_aws
          filters:
            branches:
              only: 
                - /feature\/aws\/.*/              