version: 2.1

orbs:
  silta: silta/silta@dev:master

executors:
  silta-latest:
    docker:
      - image: wunderio/silta-circleci:latest

workflows:
  version: 2
  build_deploy:
    jobs:
      - silta/simple-build-deploy: &build-deploy
          name: 'simple-build-deploy'
          executor: silta-latest
          build_folder: hello

          # Use a local chart during development. 
          # Don't copy this! We only use following 2 lines for chart development in this repository.
          chart_name: "./charts/simple"
          chart_repository: ""

          #Executes after logging into cluster, docker
          pre-release:
            - run:
                name: Build local helm dependencies
                command: |
                  helm dependency build ./charts/simple
            - run:
                name: Dry-run helm install
                command: |
                  helm install --dry-run --generate-name ./charts/simple
          context: 'silta_dev'
          silta_config: silta/silta.yml
          filters:
            branches:
              ignore: 'production'

