version: 2.1

orbs:
  silta: silta/silta@dev:master

executors:
  silta-latest:
    docker:
      - image: wunderio/silta-circleci:latest

workflows:
  version: 2
  build_deploy:
    jobs:
      - silta/simple-build-deploy: &build-deploy
          name: 'simple-development-build'
          executor: silta-latest
          # Use a local chart during development. 
          # Don't copy this! We only use following 2 lines for chart development in this repository.
          chart_name: './charts/simple'
          chart_repository: ''
          codebase-build:
            - run:
                name: Build local helm dependencies
                command: helm dependency build ./charts/simple
            - run:
                name: Dry-run helm install
                command: helm install --dry-run --generate-name ./charts/simple
          context: 'silta_dev'
          filters:
            branches:
              ignore: 'production'

