{{- $context_ingress := .Values.ingress.default }}
{{- $context_ssl := .Values.ssl }}
{{- if $context_ingress.tls }}
{{- if has $context_ssl.issuer (list "letsencrypt" "letsencrypt-staging") }}
{{- include "cert-manager.api-version" . }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt
  labels:
    {{- include "simple.release_labels" . | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-tls
  dnsNames:
  - {{ template "simple.domain" . }}
  issuerRef:
    name: {{ $context_ssl.issuer }}
    kind: ClusterIssuer
{{- if not ( .Capabilities.APIVersions.Has "cert-manager.io/v1" ) }}
  acme:
    config:
      - http01:
          ingress: {{ .Release.Name }}-simple
        domains:
          - {{ template "simple.domain" . }}
{{- end }}
---

{{- else if eq $context_ssl.issuer "selfsigned" }}
{{- include "cert-manager.api-version" . }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt
  labels:
    {{- include "simple.release_labels" . | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-tls
  duration: 2160h
  renewBefore: 150h 
  commonName: {{ template "simple.domain" . }}
  dnsNames:
  - {{ template "simple.domain" . }}
  issuerRef:
    name: {{ $context_ssl.issuer }}
    kind: ClusterIssuer
---

{{- else if eq $context_ssl.issuer "custom" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
  labels:
    {{- include "simple.release_labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.ca: {{ $context_ssl.ca | b64enc }}
  tls.crt: {{ $context_ssl.crt | b64enc }}
  tls.key: {{ $context_ssl.key | b64enc }}
---
{{- end }}

# Certificates for exposeDomains 

{{- range $index, $domain := .Values.exposeDomains }}
{{- $domain := merge $domain $.Values.exposeDomainsDefaults }}
{{- if $domain.ssl }}
{{- if $domain.ssl.enabled }}
{{- if has $domain.ssl.issuer (list "letsencrypt" "letsencrypt-staging") }}
{{- include "cert-manager.api-version" $ }}
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-crt-{{ $index }}
  labels:
    {{- include "simple.release_labels" $ | nindent 4 }}
spec:
  secretName: {{ $.Release.Name }}-tls-{{ $index }}
  dnsNames:
  - {{ $domain.hostname }}
  issuerRef:
    name: {{ $domain.ssl.issuer }}
    kind: ClusterIssuer
{{- if not ( $.Capabilities.APIVersions.Has "cert-manager.io/v1" ) }}
  acme:
    config:
      - http01:
          ingress: {{ $.Release.Name }}-simple-{{ $domain.ingress }}
        domains:
          - {{ $domain.hostname }}
{{- end }}
---

{{- else if eq $domain.ssl.issuer "selfsigned" }}
{{- include "cert-manager.api-version" $ }}
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-crt-{{ $index }}
  labels:
    {{- include "simple.release_labels" $ | nindent 4 }}
spec:
  secretName: {{ $.Release.Name }}-tls-{{ $index }}
  duration: 2160h
  renewBefore: 150h 
  commonName: {{ $domain.hostname }}
  dnsNames:
  - {{ $domain.hostname }}
  issuerRef:
    name: {{ $domain.ssl.issuer }}
    kind: ClusterIssuer
---

{{- else if eq $domain.ssl.issuer "custom" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-tls-{{ $index }}
  labels:
    {{- include "simple.release_labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $domain.ssl.ca | default "" | b64enc }}
  tls.crt: {{ $domain.ssl.crt | default "" | b64enc }}
  tls.key: {{ $domain.ssl.key | default "" | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
