apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
  labels:
    {{ include "simple.release_labels" . | indent 4 }}
data:
  nginx_conf: |
    user                            nginx;                                                 
    worker_processes                auto;

    error_log                       /proc/self/fd/2 {{ .Values.nginx.loglevel }};                                 
                                                                                          
    events {                                                                               
        worker_connections          1024;                                                  
        multi_accept                on;                                                    
    }                                                                                      
                                                                                          
    http {

        set_real_ip_from                {{ .Values.nginx.basicauth.realipfrom }};
        real_ip_header                  X-Forwarded-For;

        include                     /etc/nginx/mime.types;                                 
        default_type                application/octet-stream;                              
                                                                                          
        log_format  main            '$remote_addr - $remote_user [$time_local] "$request" '
                                    '$status $body_bytes_sent "$http_referer" '
                                    '"$http_user_agent" "$http_x_forwarded_for"';
                                                            
                                                                                                              
        access_log                  /proc/self/fd/1 main;
                                              
        send_timeout                60s;       
        sendfile                    on;        
        client_body_timeout         60s;       
        client_header_timeout       60s;                                                                                                                   
        client_max_body_size        32m;                                                                                                                   
        client_body_buffer_size     16k;                                                                                                                   
        client_header_buffer_size   4k;                                                                                                                    
        large_client_header_buffers 8 16K;                                                                                                                 
        keepalive_timeout           75s;                                                                                                                   
        keepalive_requests          100;                                                                                                                   
        reset_timedout_connection   off;                                                                                                                   
        tcp_nodelay                 on;                                                                                                                    
        tcp_nopush                  on;                                                                                                                    
        server_tokens               off;                                                                                                                   
                                                                                                                                                          
        ## upload_progress             uploads 1m;          
                                              
        gzip                        on;                      
        gzip_buffers                16 8k;     
        gzip_comp_level             1;         
        gzip_http_version           1.1;       
        gzip_min_length             20;        
        gzip_types                  text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascrip
        gzip_vary                   on;                                                                                                                    
        gzip_proxied                any;       
        gzip_disable                msie6;                                                                                                                 
                                                                                                                                                          
        ## https://www.owasp.org/index.php/List_of_useful_HTTP_headers.
        add_header                  X-Frame-Options SAMEORIGIN;                                                                                            
        add_header                  X-Content-Type-Options nosniff;
        add_header                  Strict-Transport-Security max-age=31536000;
        add_header                  X-XSS-Protection '1; mode=block';
                                                                    
        map $uri $no_slash_uri {                                                                                                                           
            ~^/(?<no_slash>.*)$ $no_slash;                                                                                                                 
        }                                                            
                                                                                                                                                          
        include conf.d/*.conf;                                                                                                                             
    }     

  simple_conf: |                          
    map $http_x_forwarded_proto $fastcgi_https {                                                        
        default $https;                                            
        http '';                          
        https on;                          
    }                                      
                                          
    server {                               
        server_name simple;                          
        listen 80;          
                                        
        root /var/www/html/web;                                     
        index index.html;
                                                                              
        include fastcgi.conf;

        {{ include "simple.basicauth" . | indent 6}}

        # Custom configuration gets included here
        {{- .Values.nginx.serverExtraConfig | nindent 8 -}}
         
        location = /robots.txt {
          access_log off;
          {{- if not .Values.nginx.robotsTxt.allow }}
            add_header Content-Type text/plain;
            return 200 'User-agent: *\nDisallow: /';
          {{- end}}
        } 

        location / {                                                                                                              
            ## Most sites won't have configured favicon
            ## and since its always grabbed, turn it off in access log
            ## and turn off it's not-found error in the error log
            location = /favicon.ico { access_log off; log_not_found off;  }

            ## Same for apple-touch-icon files
            location = /apple-touch-icon.png { access_log off; log_not_found off; }
            location = /apple-touch-icon-precomposed.png { access_log off; log_not_found off; }

            ## Rather than just denying .ht* in the config, why not deny
            ## access to all .invisible files
            location ~ /\. { return 404; access_log off; log_not_found off; }
        }                                                                                                                                                                                                                                                                                                                                     
    }
