apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-simple
  labels:
    {{ include "simple.release_labels" . | indent 4 }}
  annotations:
    {{- if (index .Values "silta-release").downscaler.enabled }}
    auto-downscale/down: "false"
    {{- end }}
    {{- if .Values.cluster }}
    {{- if and (eq .Values.cluster.type "gke") (.Values.backendConfig) }}
    cloud.google.com/backend-config: '{"default":"{{ .Release.Name }}-simple"}'
    {{- end }}
    {{- if .Values.cluster.vpcNative }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    {{- end }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    {{ include "simple.release_labels" . | indent 4 }}
