apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-simple
  labels:
    {{ include "simple.release_labels" . | indent 4 }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
  selector:
    {{ include "simple.release_labels" . | indent 4 }}